version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: 'tfl:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - RUN_MIGRATIONS=${RUN_MIGRATIONS}
    ports:
      - 5555:80
    build:
      context: .
      dockerfile: app.Dockerfile
    command: ["./wait-for-it.sh", "db:5432", "--strict" , "--timeout=300" , "--" , "/start.sh"]

volumes:
  db:
    driver: local

