"""Remove line service_type relationship

Revision ID: 076b20aef6de
Revises: 573efeacac6e
Create Date: 2022-03-21 01:55:56.950520

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '076b20aef6de'
down_revision = '573efeacac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('line_service_type_id_fkey', 'line', type_='foreignkey')
    op.drop_column('line', 'service_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('service_type_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('line_service_type_id_fkey', 'line', 'servicetype', ['service_type_id'], ['id'])
    # ### end Alembic commands ###
