"""Add line disruption table

Revision ID: 1af5297967f5
Revises: 1e2d83cc62f5
Create Date: 2022-03-23 00:56:48.784820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1af5297967f5"
down_revision = "1e2d83cc62f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linedisruption",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("category_description", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("affected_routes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("affected_stops", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("closure_text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linedisruption_id"), "linedisruption", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_linedisruption_id"), table_name="linedisruption")
    op.drop_table("linedisruption")
    # ### end Alembic commands ###
