"""Add all models

Revision ID: 1e2d83cc62f5
Revises: c9fc4f63cf64
Create Date: 2022-03-22 23:58:31.953697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e2d83cc62f5"
down_revision = "c9fc4f63cf64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mode",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_tfl_service", sa.Boolean(), nullable=False),
        sa.Column("is_fare_paying", sa.Boolean(), nullable=False),
        sa.Column("is_scheduled_service", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_mode_id"), "mode", ["id"], unique=False)
    op.create_table(
        "servicetype",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_servicetype_id"), "servicetype", ["id"], unique=False)
    op.create_table(
        "line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tfl_id", sa.String(), nullable=True),
        sa.Column("tfl_name", sa.String(), nullable=True),
        sa.Column("mode_id", sa.String(), nullable=False),
        sa.Column("line_statuses", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("route_sections", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("disruptions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mode_id"],
            ["mode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_line_id"), "line", ["id"], unique=False)
    op.create_index(op.f("ix_line_tfl_id"), "line", ["tfl_id"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("schedule_time", sa.DateTime(), nullable=True),
        sa.Column("lines", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("job_id", sa.String(length=191), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["apscheduler_jobs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_id"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_line_tfl_id"), table_name="line")
    op.drop_index(op.f("ix_line_id"), table_name="line")
    op.drop_table("line")
    op.drop_index(op.f("ix_servicetype_id"), table_name="servicetype")
    op.drop_table("servicetype")
    op.drop_index(op.f("ix_mode_id"), table_name="mode")
    op.drop_table("mode")
    # ### end Alembic commands ###
