"""Add line related models

Revision ID: 52a0ac7c2fd5
Revises: 968d4090aaa3
Create Date: 2022-03-21 01:27:24.252716

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "52a0ac7c2fd5"
down_revision = "968d4090aaa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mode",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_tfl_service", sa.Boolean(), nullable=False),
        sa.Column("is_fare_paying", sa.Boolean(), nullable=False),
        sa.Column("is_scheduled_service", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_mode_id"), "mode", ["id"], unique=False)
    op.create_table(
        "servicetype",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_servicetype_id"), "servicetype", ["id"], unique=False)
    op.create_table(
        "line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("mode_id", sa.String(), nullable=False),
        sa.Column("service_type_id", sa.String(), nullable=False),
        sa.Column("line_statuses", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("route_sections", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("disruptions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mode_id"],
            ["mode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_type_id"],
            ["servicetype.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_line_id"), "line", ["id"], unique=False)
    op.drop_constraint("task_job_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(
        None, "task", "apscheduler_jobs", ["job_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.create_foreign_key(
        "task_job_id_fkey", "task", "apscheduler_jobs", ["job_id"], ["id"]
    )
    op.drop_index(op.f("ix_line_id"), table_name="line")
    op.drop_table("line")
    op.drop_index(op.f("ix_servicetype_id"), table_name="servicetype")
    op.drop_table("servicetype")
    op.drop_index(op.f("ix_mode_id"), table_name="mode")
    op.drop_table("mode")
    # ### end Alembic commands ###
