"""Fix id in Line model

Revision ID: 573efeacac6e
Revises: 52a0ac7c2fd5
Create Date: 2022-03-21 01:43:46.889107

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '573efeacac6e'
down_revision = '52a0ac7c2fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
