"""Fill data

Revision ID: 600ab7d04382
Revises: f5bfdae5368d
Create Date: 2022-03-23 02:10:07.560173

"""
from alembic import op

from ..data.modes import MODE_INITIAL, MODE_TRUNCATE
from ..data.servicetype import SERVICE_TYPE_INITIAL, SERVICE_TYPE_TRUNCATE


# revision identifiers, used by Alembic.
revision = "600ab7d04382"
down_revision = "f5bfdae5368d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(MODE_INITIAL)
    op.execute(SERVICE_TYPE_INITIAL)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(SERVICE_TYPE_TRUNCATE)
    op.execute(MODE_TRUNCATE)
    # ### end Alembic commands ###
