"""Add job_id in Task model

Revision ID: 880b6103b9fb
Revises: 65ff77f9057b
Create Date: 2022-03-20 21:16:30.771563

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "880b6103b9fb"
down_revision = "65ff77f9057b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("job_id", sa.String(length=191), nullable=True))
    op.create_foreign_key(None, "task", "apscheduler_jobs", ["job_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "job_id")
    # ### end Alembic commands ###
