"""Remove delete cascade

Revision ID: 968d4090aaa3
Revises: fc7118a326e5
Create Date: 2022-03-21 00:53:07.897246

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '968d4090aaa3'
down_revision = 'fc7118a326e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_job_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'apscheduler_jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_job_id_fkey', 'task', 'apscheduler_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
