"""Cascade deletion of task to job

Revision ID: fc7118a326e5
Revises: 880b6103b9fb
Create Date: 2022-03-20 21:52:00.666288

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fc7118a326e5"
down_revision = "880b6103b9fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_job_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(
        None, "task", "apscheduler_jobs", ["job_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.create_foreign_key(
        "task_job_id_fkey", "task", "apscheduler_jobs", ["job_id"], ["id"]
    )
    # ### end Alembic commands ###
